PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Controllers/RecetasMedicasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace PL.Controllers
{
    public class RecetasMedicasController : Controller
    {
        [HttpGet]
        public IActionResult GetAllReceta()
        {
            ML.RecetasMedicas recetas = new ML.RecetasMedicas();

            ML.Result result = BL.RecetasMedicas.GetAll();

            if (result.Correct)
            {
                recetas.Recetas = result.Objects;
            }
            else
            {
                ViewBag.Mensaje = result.ErrorMessage;
            }

            return View(recetas);
        }


        [HttpPost]
        public IActionResult GetAllReceta(ML.RecetasMedicas receta)
        {
            ML.Result result = BL.RecetasMedicas.GetAll();
            receta = new ML.RecetasMedicas();
            receta.Recetas = result.Objects;
            return View(receta);
        }

        [HttpGet]
        public IActionResult Add(int? IdReceta)
        {
            ML.RecetasMedicas recetas = new ML.RecetasMedicas();
            recetas.Paciente = new ML.Paciente();

            ML.Result resultPaciente = BL.Paciente.GetAll();

            if (IdReceta != 0) //update
            {
                ML.Result resultReceta = BL.RecetasMedicas.GatById(IdReceta.Value);

                if (resultReceta.Correct)
                {
                    recetas = (ML.RecetasMedicas)resultReceta.Object;
                    
                    recetas.Paciente.Pacientes = resultPaciente.Objects;
                }   
            }
            else //add
            {
                recetas.Paciente.Pacientes = resultPaciente.Objects;
            }
            return View(recetas);
        }

        [HttpPost]
        public IActionResult Add(ML.RecetasMedicas recetas)
        {
            if(recetas.IdRecetas == 0) //add
            {
                ML.Result result = BL.RecetasMedicas.Add(recetas);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se incerto correctamente";
                }
                else
                {
                    ViewBag.Error = result.ErrorMessage;
                }
            }
            else //update
            {
                ML.Result result = BL.RecetasMedicas.Update(recetas);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se actualizo correctamente";
                }
                else
                {
                    ViewBag.Error = result.ErrorMessage;
                }
            }
            return PartialView("Modal");
        }

        public IActionResult Dell(int IdReceta)
        {
            ML.Result result = BL.RecetasMedicas.Dell(IdReceta);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se elimino correctamente";
            }
            else
            {
                ViewBag.Error = result.ErrorMessage;
            }

            return PartialView("Modal");
        }


    }
}

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/RecetasMedicas/Add.cshtml
@model ML.RecetasMedicas

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
@using (Html.BeginForm("Add", "RecetasMedicas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model=> model.IdRecetas);

    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(model => model.Paciente.IdPaciente, new { @class = "hidden" })

            @Html.DropDownListFor(model => model.Paciente.IdPaciente, new SelectList(Model.Paciente.Pacientes, "IdPaciente", "Nombre"), "Selecciona un paciente", new { @class = "form-controls" })
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.FechaConsulta, new { @class = "hidden" })
            @Html.TextBoxFor(model => model.FechaConsulta, new { @class = "coll-auto" , @placeholder = "DD-MM-AAAA"})
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.Diagnostico, new { @class = "hidden" })
            @Html.TextBoxFor(model => model.Diagnostico, new { @class = "coll-auto"})
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.NombreMedico, new { @class = "hidden" })
            @Html.TextBoxFor(model => model.NombreMedico, new { @class = "coll-auto"})
        </div>

    </div>

    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(model => model.NotasAdicionales, new { @class = "hidden" })
            @Html.TextBoxFor(model => model.NotasAdicionales, new { @class = "coll-auto"})
        </div>

        <div class="col-md-1">
            <input type="submit" data-toggle="modal" class="btn btn-success" value="Guardar" />
        </div>
        <div class="col-md-1">
            <a id="back" class="btn btn-danger" href="@Url.Action("GetAllReceta", "RecetasMedicas")">Volver</a>
        </div>

    </div>

    

}
}

PL/Views/RecetasMedicas/GetAllReceta.cshtml
@model ML.RecetasMedicas;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{

@if (Model.Recetas != null)
{
    <div class="row">
        <div class="col-md-12">

            <a class="btn btn-success" href=@Url.Action("Add","RecetasMedicas" , new {IdReceta = 0})>Agregar nueva receta</a>

            <table class="table">

                <thead>
                    <tr>
                        <th>Fecha consulta</th>
                        <th>Diagnostico</th>
                        <th>Nombre del Medico</th>
                        <th>Notas Adicionales</th>
                        <th>Actualizar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                @foreach (ML.RecetasMedicas recetas in Model.Recetas)
                {
                    <tr>

                        <td>@recetas.FechaConsulta</td>
                        <td>@recetas.Diagnostico</td>
                        <td>@recetas.NombreMedico</td>
                        <td>@recetas.NotasAdicionales</td>

                        <td>
                            <a class="btn btn-warning" href="@Url.Action("Add","RecetasMedicas",new { IdReceta = recetas.IdRecetas } )">Actualizar </a>
                        </td>

                        <td>
                            <a class="btn btn-danger" href="@Url.Action("Dell","RecetasMedicas", new {IdReceta = recetas.IdRecetas, onclick="return confirm('Estas seguro que deseas eliminar esta receta?');" } )"> Eliminar</a>
                        </td>

                    </tr>
                }

                <tbody>


                </tbody>

            </table>
        </div>
    </div>
}

}

PL/Views/RecetasMedicas/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Mensaje</p>
            </div>
            <div class="modal-footer">
                
                    @Html.ActionLink("Regresar", "GetAllReceta", "RecetasMedicas", new { @class = "btn btn-primary" })

            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="RecetasMedicas" asp-controller="RecetasMedicas" asp-action="GetAllReceta">Recetas</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>